<#
.SYNOPSIS
    Generates Windows App SDK C++ headers from WINMD/IDL files.

.DESCRIPTION
    Downloads processing is handled by the caller (build.cake). This script
    takes the extracted NuGet root and runs winmdidl + midlrt to produce
    the C++ headers ANGLE needs.

    Must be run in a vcvarsall environment so midlrt can find cl.exe.

.PARAMETER Path
    Root of the extracted Microsoft.WindowsAppSDK NuGet package.
#>
param(
    [Parameter(Mandatory)]
    [string]$Path
)

$ErrorActionPreference = 'Stop'

$includePath = Join-Path $Path 'include'
$libPath = Join-Path $Path 'lib'
$uapVersion = '10.0.18362'

# Ensure include directory exists
if (-not (Test-Path $includePath)) {
    New-Item -ItemType Directory -Path $includePath | Out-Null
}

# Find Windows SDK bin directory
$winSdkDir = $env:WindowsSdkDir
if (-not $winSdkDir) {
    $winSdkDir = 'C:\Program Files (x86)\Windows Kits\10'
}
$sdkVersion = Get-ChildItem (Join-Path $winSdkDir 'bin') -Directory -Filter '10.0.*' |
    Sort-Object Name -Descending |
    Select-Object -First 1
if (-not $sdkVersion) {
    throw "Could not find Windows SDK bin directory under $winSdkDir"
}
$winSdkBin = Join-Path $sdkVersion.FullName 'x64'
$winmdidl = Join-Path $winSdkBin 'winmdidl.exe'
$midlrt = Join-Path $winSdkBin 'midlrt.exe'

Write-Host "Using Windows SDK: $($sdkVersion.Name)"
Write-Host "WinAppSDK path: $Path"

# Both winmdidl and midlrt run with CWD set to the include directory
# (midlrt resolves imported IDL files relative to CWD)
Push-Location $includePath
try {
    # Process all WINMD files with winmdidl.exe
    # Discover all .winmd files under the lib directory so new namespaces in
    # newer WinAppSDK versions are handled automatically.
    $metadataDirs = @(
        'C:\Windows\System32\WinMetadata'
        (Join-Path $libPath "uap$uapVersion")
        (Join-Path $libPath 'uap10.0')
    )
    $winmdFiles = Get-ChildItem $libPath -Filter '*.winmd' -Recurse

    foreach ($winmd in $winmdFiles) {
        # Use the first IDL that would be produced as a stamp file
        $stampName = [System.IO.Path]::GetFileNameWithoutExtension($winmd.Name) + '.idl'
        $stampFile = Join-Path $includePath $stampName
        if (Test-Path $stampFile) { continue }

        Write-Host "  winmdidl: $($winmd.FullName)"
        $metadataArgs = $metadataDirs | ForEach-Object { "/metadata_dir:$_" }
        & $winmdidl $winmd.FullName @metadataArgs "/outdir:$includePath" /nologo
        if ($LASTEXITCODE -ne 0) { throw "winmdidl failed for $($winmd.Name)" }
    }

    # Process IDL files with midlrt.exe
    # Process all .idl files generated by winmdidl (rather than a hardcoded list,
    # so new namespaces added in newer WinAppSDK versions are handled automatically)
    $idlFiles = Get-ChildItem $includePath -Filter '*.idl' | Select-Object -ExpandProperty Name

    foreach ($idl in $idlFiles) {
        $noExt = [System.IO.Path]::GetFileNameWithoutExtension($idl)
        $headerFile = Join-Path $includePath "$noExt.h"
        if (Test-Path $headerFile) { continue }

        Write-Host "  midlrt: $idl"
        & $midlrt $idl /metadata_dir C:\Windows\System32\WinMetadata /ns_prefix /nomidl /nologo
        if ($LASTEXITCODE -ne 0) {
            # Some IDL files reference metadata from external packages that midlrt
            # cannot resolve (e.g. Microsoft.Windows.ApplicationModel.Resources).
            # Create an empty stub header so downstream #includes don't fail —
            # ANGLE doesn't use types from these namespaces.
            Write-Host "    WARNING: midlrt failed for $idl (exit code $LASTEXITCODE), creating stub header"
            $guard = ($noExt -replace '\.', '_').ToUpper() + '_H'
            Set-Content -Path $headerFile -Value @"
#pragma once
// Stub header — midlrt could not process $idl
#ifndef $guard
#define $guard
#endif // $guard
"@
        }
    }
} finally {
    Pop-Location
}

Write-Host "Windows App SDK header generation complete."
