using SkiaSharp.Triage.Models;

namespace SkiaSharp.Triage.Dashboard.Services;

// ── Dashboard wrapper (generated by collector) ───────────────────

public record TriageData(
    DateTime GeneratedAt,
    int TotalCount,
    TriageSummaryStats Summary,
    List<LabelCount> ByType,
    List<LabelCount> ByArea,
    List<LabelCount> ByAction,
    List<LabelCount> BySeverity,
    List<TriagedIssue> Issues
);

public record TriageSummaryStats(
    int NeedsInvestigation,
    int Closeable,
    int QuickWins,
    int NeedsHumanReview,
    int Regressions
);
