<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TFMPrevious)-ios$(TPViOSPrevious);$(TFMCurrent)-ios$(TPViOSCurrent)</TargetFrameworks>
    <PackagingGroup>SkiaSharp</PackagingGroup>
    <Title>$(PackagingGroup) - Native Assets for iOS</Title>
    <HasNativeSymbolPackage>true</HasNativeSymbolPackage>
  </PropertyGroup>
  <ItemGroup>
    <NativeRuntimeBundle Include="$(NativeOutputPath)ios\libSkiaSharp.framework" ModuleName="libSkiaSharp" PackagePath="runtimes\ios\native\libSkiaSharp.framework" />
    <NativeRuntimeBundle Include="$(NativeOutputPath)iossimulator\libSkiaSharp.framework" ModuleName="libSkiaSharp" PackagePath="runtimes\iossimulator\native\libSkiaSharp.framework" />
    <NativeSymbolBundle Include="$(NativeOutputPath)ios\libSkiaSharp\arm64.xcarchive\dSYMs\libSkiaSharp.framework.dSYM" DwarfName="libSkiaSharp" PackagePath="runtimes\ios\native\symbols\arm64\libSkiaSharp.framework.dSYM" />
    <NativeSymbolBundle Include="$(NativeOutputPath)ios\libSkiaSharp\x86_64.xcarchive\dSYMs\libSkiaSharp.framework.dSYM" DwarfName="libSkiaSharp" PackagePath="runtimes\ios\native\symbols\x86_64\libSkiaSharp.framework.dSYM" />
    <NativeSymbolBundle Include="$(NativeOutputPath)iossimulator\libSkiaSharp\arm64.xcarchive\dSYMs\libSkiaSharp.framework.dSYM" DwarfName="libSkiaSharp" PackagePath="runtimes\iossimulator\native\symbols\arm64\libSkiaSharp.framework.dSYM" />
    <NativeSymbolBundle Include="$(NativeOutputPath)iossimulator\libSkiaSharp\x86_64.xcarchive\dSYMs\libSkiaSharp.framework.dSYM" DwarfName="libSkiaSharp" PackagePath="runtimes\iossimulator\native\symbols\x86_64\libSkiaSharp.framework.dSYM" />
  </ItemGroup>
  <Target Name="IncludeAdditionalTfmSpecificPackageFiles">
    <ItemGroup>
      <TfmSpecificPackageFile Include="buildTransitive\SkiaSharp.targets" PackagePath="buildTransitive\$(NuGetShortFolderName)\$(PackageId).targets" />
    </ItemGroup>
  </Target>
</Project>