# TODO: implement features

trigger:
  - master

variables:
  FeatureNamePrefix: 'feature/'
  FeatureName: ''
  GIT_SHA: $(Build.SourceVersion)
  GIT_BRANCH_NAME: $(Build.SourceBranchName)
  BUILD_NUMBER: $(Build.BuildId)
  FEATURE_NAME: $(FeatureName)

jobs:
  - job: prepare
    pool: 
      vmImage: ubuntu-16.04
    steps:
      - script: |
          echo Preparing to build $(GIT_SHA) on branch $(GIT_BRANCH_NAME)...
          echo Build started for $(BUILD_NUMBER).
