namespace SkiaSharp.Views.WinUI.Native
{
    static runtimeclass PropertySetExtensions
    {
        static void AddSingle(Windows.Foundation.Collections.PropertySet propertySet, String key, Single value);
        static void AddSize(Windows.Foundation.Collections.PropertySet propertySet, String key, Windows.Foundation.Size value);
    }
}
