<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TFMPrevious)-ios$(TPViOSPrevious);$(TFMCurrent)-ios$(TPViOSCurrent)</TargetFrameworks>
    <PackagingGroup>HarfBuzzSharp</PackagingGroup>
    <Title>$(PackagingGroup) - Native Assets for iOS</Title>
  </PropertyGroup>
  <ItemGroup>
    <NativeRuntimeBundle Include="..\..\output\native\ios\libHarfBuzzSharp.framework" ModuleName="libHarfBuzzSharp" PackagePath="runtimes\ios\native\libHarfBuzzSharp.framework" />
    <NativeRuntimeBundle Include="..\..\output\native\iossimulator\libHarfBuzzSharp.framework" ModuleName="libHarfBuzzSharp" PackagePath="runtimes\iossimulator\native\libHarfBuzzSharp.framework" />
    <NativeSymbolBundle Include="..\..\output\native\ios\libHarfBuzzSharp\arm64.xcarchive\dSYMs\libHarfBuzzSharp.framework.dSYM" DwarfName="libHarfBuzzSharp" PackagePath="runtimes\ios\native\symbols\arm64\libHarfBuzzSharp.framework.dSYM" />
    <NativeSymbolBundle Include="..\..\output\native\ios\libHarfBuzzSharp\x86_64.xcarchive\dSYMs\libHarfBuzzSharp.framework.dSYM" DwarfName="libHarfBuzzSharp" PackagePath="runtimes\ios\native\symbols\x86_64\libHarfBuzzSharp.framework.dSYM" />
    <NativeSymbolBundle Include="..\..\output\native\iossimulator\libHarfBuzzSharp\arm64.xcarchive\dSYMs\libHarfBuzzSharp.framework.dSYM" DwarfName="libHarfBuzzSharp" PackagePath="runtimes\iossimulator\native\symbols\arm64\libHarfBuzzSharp.framework.dSYM" />
    <NativeSymbolBundle Include="..\..\output\native\iossimulator\libHarfBuzzSharp\x86_64.xcarchive\dSYMs\libHarfBuzzSharp.framework.dSYM" DwarfName="libHarfBuzzSharp" PackagePath="runtimes\iossimulator\native\symbols\x86_64\libHarfBuzzSharp.framework.dSYM" />
  </ItemGroup>
  <Target Name="IncludeAdditionalTfmSpecificPackageFiles">
    <ItemGroup>
      <TfmSpecificPackageFile Include="buildTransitive\HarfBuzzSharp.targets" PackagePath="buildTransitive\$(NuGetShortFolderName)\$(PackageId).targets" />
    </ItemGroup>
  </Target>
</Project>