//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("SkiaSharp.Workbooks")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("SkiaSharp")]
[assembly: AssemblyVersion("1.57.2.0")]
[assembly: AssemblyFileVersion("1.57.2.0")]
[assembly: AssemblyInformationalVersion("1.57.2.0-{GIT_SHA}")]
[assembly: AssemblyCopyright("Microsoft")]
[assembly: AssemblyTrademark("")]

