<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TFMPrevious)-tvos$(TPVtvOSPrevious);$(TFMCurrent)-tvos$(TPVtvOSCurrent)</TargetFrameworks>
    <PackagingGroup>SkiaSharp</PackagingGroup>
    <Title>$(PackagingGroup) - Native Assets for tvOS</Title>
    <HasNativeSymbolPackage>true</HasNativeSymbolPackage>
  </PropertyGroup>
  <ItemGroup>
    <NativeRuntimeBundle Include="$(NativeOutputPath)tvos\libSkiaSharp.framework" ModuleName="libSkiaSharp" PackagePath="runtimes\tvos\native\libSkiaSharp.framework" />
    <NativeRuntimeBundle Include="$(NativeOutputPath)tvossimulator\libSkiaSharp.framework" ModuleName="libSkiaSharp" PackagePath="runtimes\tvossimulator\native\libSkiaSharp.framework" />
    <NativeSymbolBundle Include="$(NativeOutputPath)tvos\libSkiaSharp\arm64.xcarchive\dSYMs\libSkiaSharp.framework.dSYM" DwarfName="libSkiaSharp" PackagePath="runtimes\tvos\native\symbols\arm64\libSkiaSharp.framework.dSYM" />
    <NativeSymbolBundle Include="$(NativeOutputPath)tvos\libSkiaSharp\x86_64.xcarchive\dSYMs\libSkiaSharp.framework.dSYM" DwarfName="libSkiaSharp" PackagePath="runtimes\tvos\native\symbols\x86_64\libSkiaSharp.framework.dSYM" />
    <NativeSymbolBundle Include="$(NativeOutputPath)tvossimulator\libSkiaSharp\arm64.xcarchive\dSYMs\libSkiaSharp.framework.dSYM" DwarfName="libSkiaSharp" PackagePath="runtimes\tvossimulator\native\symbols\arm64\libSkiaSharp.framework.dSYM" />
    <NativeSymbolBundle Include="$(NativeOutputPath)tvossimulator\libSkiaSharp\x86_64.xcarchive\dSYMs\libSkiaSharp.framework.dSYM" DwarfName="libSkiaSharp" PackagePath="runtimes\tvossimulator\native\symbols\x86_64\libSkiaSharp.framework.dSYM" />
  </ItemGroup>
  <Target Name="IncludeAdditionalTfmSpecificPackageFiles">
    <ItemGroup>
      <TfmSpecificPackageFile Include="buildTransitive\SkiaSharp.targets" PackagePath="buildTransitive\$(NuGetShortFolderName)\$(PackageId).targets" />
    </ItemGroup>
  </Target>
</Project>