<Project>
  <Target Name="_SkiaSharpPreferLegacyNoDependencies"
          BeforeTargets="AssignTargetPaths"
          Condition="'@(Content)' != ''">
    <ItemGroup>
      <_SkiaSharpLegacyNoDependencies Include="@(Content->WithMetadataValue('DefiningProjectName', 'SkiaSharp.NativeAssets.Linux.NoDependencies'))" />
      <_SkiaSharpLegacyRegular Include="@(Content->WithMetadataValue('DefiningProjectName', 'SkiaSharp.NativeAssets.Linux'))" />
      <_SkiaSharpLegacyUnmatched Include="@(_SkiaSharpLegacyRegular)" />
      <_SkiaSharpLegacyUnmatched Remove="@(_SkiaSharpLegacyNoDependencies)"
                                 MatchOnMetadata="Link" MatchOnMetadataOptions="CaseInsensitive" />
      <_SkiaSharpLegacyReplaced Include="@(_SkiaSharpLegacyRegular)" Exclude="@(_SkiaSharpLegacyUnmatched)" />
      <_SkiaSharpLegacyReplaced Remove="@(_SkiaSharpLegacyNoDependencies)"
                                MatchOnMetadata="FullPath" MatchOnMetadataOptions="CaseInsensitive" />
      <Content Remove="@(_SkiaSharpLegacyReplaced)" />
    </ItemGroup>
  </Target>
</Project>
