name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] <title>"
labels: ["type/feature-request"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to let us know about a new way we can add more value!
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is that this new feature will solve.
      placeholder: I need to do X, but the API is missing from the C# binding.
  - type: textarea
    id: solution
    validations:
      required: true
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of what you want to happen or how you would like a new feature to work.
      placeholder: I would like to see API X and API Y exposed in the C# binding.
  - type: textarea
    id: alternatives
    validations:
      required: true
    attributes:
      label: Describe alternatives you have considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I tried to use API A nd API B, but they were not sufficient.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mono/SkiaSharp/blob/main/CODE-OF-CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
