<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <GenerateTestingPlatformEntryPoint>false</GenerateTestingPlatformEntryPoint>
    <SkipGenerateAssemblyVersionInfo>true</SkipGenerateAssemblyVersionInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="1.9.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.HangDump" Version="1.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\samples\Gallery\Shared\SkiaSharpSample.Shared.csproj" />
    <Compile Include="..\..\samples\Gallery\Maui\GalleryFilters.cs" Link="GalleryFilters.cs" />
  </ItemGroup>

  <Import Project="..\..\binding\IncludeNativeAssets.SkiaSharp.targets" />
  <Import Project="..\..\binding\IncludeNativeAssets.HarfBuzzSharp.targets" />

</Project>
