<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TFMPrevious)-maccatalyst$(TPVMacCatalystPrevious);$(TFMCurrent)-maccatalyst$(TPVMacCatalystCurrent)</TargetFrameworks>
    <PackagingGroup>HarfBuzzSharp</PackagingGroup>
    <Title>$(PackagingGroup) - Native Assets for Mac Catalyst</Title>
    <HasNativeSymbolPackage>true</HasNativeSymbolPackage>
  </PropertyGroup>
  <ItemGroup>
    <PackageFile Include="$(NativeOutputPath)maccatalyst\libHarfBuzzSharp*.framework.zip" PackagePath="runtimes\maccatalyst\native\%(Filename)%(Extension)" />
    <NativeSymbolRequiredFile Include="$(NativeOutputPath)maccatalyst\libHarfBuzzSharp.framework.zip" />
    <NativeSymbolRequiredFile Include="$(NativeOutputPath)maccatalyst\libHarfBuzzSharp.framework\Versions\A\libHarfBuzzSharp" />
    <NativeSymbolPackageFile Include="$(NativeOutputPath)maccatalyst\libHarfBuzzSharp.framework\Versions\A\libHarfBuzzSharp" RuntimeIdentifier="maccatalyst" Architecture="universal" SymbolPackagePath="runtimes\maccatalyst\native\libHarfBuzzSharp.framework\Versions\A" />
    <NativeSymbolBundle Include="$(NativeOutputPath)maccatalyst\libHarfBuzzSharp\arm64.xcarchive\dSYMs\libHarfBuzzSharp.framework.dSYM" DwarfName="libHarfBuzzSharp" SymbolPackagePath="runtimes\maccatalyst\native\symbols\arm64\libHarfBuzzSharp.framework.dSYM" />
    <NativeSymbolBundle Include="$(NativeOutputPath)maccatalyst\libHarfBuzzSharp\x86_64.xcarchive\dSYMs\libHarfBuzzSharp.framework.dSYM" DwarfName="libHarfBuzzSharp" SymbolPackagePath="runtimes\maccatalyst\native\symbols\x86_64\libHarfBuzzSharp.framework.dSYM" />
  </ItemGroup>
  <Target Name="IncludeAdditionalTfmSpecificPackageFiles">
    <ItemGroup>
      <TfmSpecificPackageFile Include="buildTransitive\HarfBuzzSharp.targets" PackagePath="buildTransitive\$(NuGetShortFolderName)\$(PackageId).targets" />
    </ItemGroup>
  </Target>
</Project>