using System.Net;
using Octokit;
using SkiaSharp.ReleaseTool.Errors;
using SkiaSharp.ReleaseTool.Finishing;
using Xunit;

namespace SkiaSharp.ReleaseTool.Tests.Finishing
{
	public sealed class OctokitFinishGitHubClientTests
	{
		private static readonly Uri DraftUrl =
			new("https://github.com/mono/SkiaSharp/releases/tag/untagged-draft");

		[Fact]
		public async Task Falls_back_to_exact_draft_from_release_listing()
		{
			var listed = false;
			var client = new OctokitFinishGitHubClient(
				(_, _) => Task.FromResult<FinishGitHubRelease?>(null),
				_ =>
				{
					listed = true;
					return Task.FromResult<IReadOnlyList<FinishGitHubRelease>>(
					[
						Release("v4.151.1", isDraft: false),
						Release("v4.152.0-rc.1", isDraft: true),
					]);
				});

			var result = await client.GetReleaseAsync(
				"v4.152.0-rc.1",
				TestContext.Current.CancellationToken);

			Assert.True(listed);
			Assert.NotNull(result);
			Assert.True(result.IsDraft);
			Assert.Equal("v4.152.0-rc.1", result.TagName);
		}

		[Fact]
		public async Task Published_lookup_avoids_release_listing()
		{
			var expected = Release("v4.152.0", isDraft: false);
			var client = new OctokitFinishGitHubClient(
				(_, _) => Task.FromResult<FinishGitHubRelease?>(expected),
				_ => throw new InvalidOperationException("listing should not run"));

			var result = await client.GetReleaseAsync(
				"v4.152.0",
				TestContext.Current.CancellationToken);

			Assert.Same(expected, result);
		}

		[Fact]
		public async Task Multiple_exact_drafts_are_rejected()
		{
			var client = new OctokitFinishGitHubClient(
				(_, _) => Task.FromResult<FinishGitHubRelease?>(null),
				_ => Task.FromResult<IReadOnlyList<FinishGitHubRelease>>(
				[
					Release("v4.152.0", isDraft: true),
					Release("v4.152.0", isDraft: true),
				]));

			await Assert.ThrowsAsync<GitHubException>(() => client.GetReleaseAsync(
				"v4.152.0",
				TestContext.Current.CancellationToken));
		}

		[Fact]
		public async Task Generate_notes_uses_exact_official_request_fields()
		{
			GenerateReleaseNotesRequest? captured = null;
			var client = Client(
				generate: (request, _) =>
				{
					captured = request;
					return Task.FromResult("generated bytes");
				});

			var body = await client.GenerateReleaseNotesAsync(
				"v4.152.0",
				new string('a', 40),
				"v4.151.1",
				TestContext.Current.CancellationToken);

			Assert.Equal("generated bytes", body);
			Assert.NotNull(captured);
			Assert.Equal("v4.152.0", captured.TagName);
			Assert.Equal(new string('a', 40), captured.TargetCommitish);
			Assert.Equal("v4.151.1", captured.PreviousTagName);
		}

		[Fact]
		public async Task Create_draft_sets_every_release_field_exactly()
		{
			NewRelease? captured = null;
			var client = Client(
				create: (request, _) =>
				{
					captured = request;
					return Task.FromResult(ReleaseFrom(request, 456));
				});
			const string body = "body\nwith whitespace  ";

			var release = await client.CreateDraftAsync(
				"v4.152.0-rc.1",
				"Version 4.152.0 (Release Candidate 1)",
				new string('b', 40),
				body,
				prerelease: true,
				TestContext.Current.CancellationToken);

			Assert.Equal(456, release.Id);
			Assert.NotNull(captured);
			Assert.Equal("v4.152.0-rc.1", captured.TagName);
			Assert.Equal("Version 4.152.0 (Release Candidate 1)", captured.Name);
			Assert.Equal(new string('b', 40), captured.TargetCommitish);
			Assert.Equal(body, captured.Body);
			Assert.True(captured.Draft);
			Assert.True(captured.Prerelease);
			Assert.False(captured.GenerateReleaseNotes);
		}

		[Fact]
		public async Task Body_update_preserves_all_non_body_release_fields()
		{
			ReleaseUpdate? captured = null;
			long? capturedId = null;
			var original = Release("v4.152.0", isDraft: true) with
			{
				Id = 777,
				Body = "old",
			};
			var client = Client(
				edit: (id, request, _) =>
				{
					capturedId = id;
					captured = request;
					return Task.FromResult(ReleaseFrom(original, request));
				});

			var updated = await client.UpdateDraftBodyAsync(
				original,
				"new exact body",
				TestContext.Current.CancellationToken);

			Assert.Equal(777, capturedId);
			Assert.NotNull(captured);
			Assert.Equal(original.TagName, captured.TagName);
			Assert.Equal(original.Title, captured.Name);
			Assert.Equal(original.TargetCommitish, captured.TargetCommitish);
			Assert.Equal("new exact body", captured.Body);
			Assert.True(captured.Draft);
			Assert.Equal(original.IsPrerelease, captured.Prerelease);
			Assert.Equal("new exact body", updated.Body);
		}

		[Fact]
		public async Task Publish_patch_preserves_body_and_identity_and_only_clears_draft()
		{
			ReleaseUpdate? captured = null;
			var original = Release("v4.152.0", isDraft: true) with
			{
				Id = 778,
				Body = "approved body\n",
			};
			var client = Client(
				edit: (_, request, _) =>
				{
					captured = request;
					return Task.FromResult(ReleaseFrom(original, request));
				});

			var published = await client.PublishDraftAsync(
				original,
				TestContext.Current.CancellationToken);

			Assert.NotNull(captured);
			Assert.False(captured.Draft);
			Assert.Equal(original.Body, captured.Body);
			Assert.Equal(original.TagName, captured.TagName);
			Assert.Equal(original.Title, captured.Name);
			Assert.Equal(original.TargetCommitish, captured.TargetCommitish);
			Assert.False(published.IsDraft);
		}

		[Fact]
		public async Task Create_422_race_accepts_only_an_exact_resulting_draft()
		{
			const string body = "approved";
			var exact = Release("v4.152.0", isDraft: true) with { Body = body };
			var client = Client(
				list: _ => Task.FromResult<IReadOnlyList<FinishGitHubRelease>>([exact]),
				create: (_, _) => Task.FromException<FinishGitHubRelease>(
					new ApiException("race", HttpStatusCode.UnprocessableEntity)));

			var result = await client.CreateDraftAsync(
				exact.TagName,
				exact.Title,
				exact.TargetCommitish,
				body,
				exact.IsPrerelease,
				TestContext.Current.CancellationToken);
			Assert.Same(exact, result);

			var mismatched = exact with { Body = "different" };
			var conflict = Client(
				list: _ => Task.FromResult<IReadOnlyList<FinishGitHubRelease>>([mismatched]),
				create: (_, _) => Task.FromException<FinishGitHubRelease>(
					new ApiException("race", HttpStatusCode.Conflict)));
			await Assert.ThrowsAsync<GitHubException>(() =>
				conflict.CreateDraftAsync(
					exact.TagName,
					exact.Title,
					exact.TargetCommitish,
					body,
					exact.IsPrerelease,
					TestContext.Current.CancellationToken));
		}

		[Fact]
		public async Task Publish_409_race_accepts_only_the_same_exact_published_release()
		{
			var draft = Release("v4.152.0", isDraft: true) with { Body = "approved" };
			var published = draft with { IsDraft = false };
			var client = Client(
				published: (_, _) => Task.FromResult<FinishGitHubRelease?>(published),
				edit: (_, _, _) => Task.FromException<FinishGitHubRelease>(
					new ApiException("race", HttpStatusCode.Conflict)));

			var result = await client.PublishDraftAsync(
				draft,
				TestContext.Current.CancellationToken);

			Assert.Same(published, result);
		}

		[Fact]
		public async Task Cancellation_is_preserved_and_other_ApiExceptions_are_wrapped()
		{
			var canceled = Client(
				generate: (_, _) => Task.FromException<string>(
					new OperationCanceledException()));
			await Assert.ThrowsAsync<OperationCanceledException>(() =>
				canceled.GenerateReleaseNotesAsync(
					"v4.152.0",
					new string('a', 40),
					null,
					TestContext.Current.CancellationToken));

			var failed = Client(
				generate: (_, _) => Task.FromException<string>(
					new ApiException("failed", HttpStatusCode.Forbidden)));
			var error = await Assert.ThrowsAsync<GitHubException>(() =>
				failed.GenerateReleaseNotesAsync(
					"v4.152.0",
					new string('a', 40),
					null,
					TestContext.Current.CancellationToken));
			Assert.IsType<ApiException>(error.InnerException);
		}

		[Fact]
		public async Task Release_list_ApiException_is_wrapped()
		{
			var client = Client(
				list: _ => Task.FromException<IReadOnlyList<FinishGitHubRelease>>(
					new ApiException("failed", HttpStatusCode.Forbidden)));

			var error = await Assert.ThrowsAsync<GitHubException>(() =>
				client.GetReleaseAsync(
					"v4.152.0",
					TestContext.Current.CancellationToken));
			Assert.IsType<ApiException>(error.InnerException);
		}

		private static OctokitFinishGitHubClient Client(
			Func<string, CancellationToken, Task<FinishGitHubRelease?>>? published = null,
			Func<CancellationToken, Task<IReadOnlyList<FinishGitHubRelease>>>? list = null,
			Func<GenerateReleaseNotesRequest, CancellationToken, Task<string>>? generate = null,
			Func<NewRelease, CancellationToken, Task<FinishGitHubRelease>>? create = null,
			Func<long, ReleaseUpdate, CancellationToken, Task<FinishGitHubRelease>>? edit = null) =>
			new(
				published ?? ((_, _) => Task.FromResult<FinishGitHubRelease?>(null)),
				list ?? (_ => Task.FromResult<IReadOnlyList<FinishGitHubRelease>>([])),
				generate ?? ((_, _) => throw new NotSupportedException()),
				create ?? ((_, _) => throw new NotSupportedException()),
				edit ?? ((_, _, _) => throw new NotSupportedException()));

		private static FinishGitHubRelease ReleaseFrom(NewRelease release, long id) =>
			new(
				id,
				release.TagName,
				release.Name,
				release.Draft,
				release.Prerelease,
				release.TargetCommitish,
				release.Body,
				DraftUrl);

		private static FinishGitHubRelease ReleaseFrom(
			FinishGitHubRelease original,
			ReleaseUpdate release) =>
			original with
			{
				TagName = release.TagName,
				Title = release.Name,
				TargetCommitish = release.TargetCommitish,
				Body = release.Body,
				IsDraft = release.Draft ?? original.IsDraft,
				IsPrerelease = release.Prerelease ?? original.IsPrerelease,
			};

		private static FinishGitHubRelease Release(string tag, bool isDraft) =>
			new(
				123,
				tag,
				"Version 4.152.0",
				isDraft,
				false,
				new string('a', 40),
				"",
				DraftUrl);
	}
}
