<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(BasicTargetFrameworks)</TargetFrameworks>
    <PackagingGroup>HarfBuzzSharp</PackagingGroup>
    <Title>$(PackagingGroup) - Native Assets for Web Assembly (WASM)</Title>
  </PropertyGroup>
  <ItemGroup>
    <PackageFile Include="..\..\output\native\wasm\libHarfBuzzSharp.a\3.1.34\**\*.a" PackagePath="buildTransitive\netstandard1.0\libHarfBuzzSharp.a\3.1.34\%(RecursiveDir)%(Filename)%(Extension)" />
    <PackageFile Include="..\..\output\native\wasm\libHarfBuzzSharp.a\3.1.56\**\*.a" PackagePath="buildTransitive\netstandard1.0\libHarfBuzzSharp.a\3.1.56\%(RecursiveDir)%(Filename)%(Extension)" />
    <PackageFile Include="..\..\output\native\wasm\libHarfBuzzSharp.a\6.0.2\**\*.a" PackagePath="buildTransitive\netstandard1.0\libHarfBuzzSharp.a\6.0.2\%(RecursiveDir)%(Filename)%(Extension)" />
    <PackageFile Include="buildTransitive\HarfBuzzSharp.props" PackagePath="buildTransitive\netstandard1.0\$(PackageId).props" />
    <PackageFile Include="buildTransitive\HarfBuzzSharp.targets" PackagePath="buildTransitive\netstandard1.0\$(PackageId).targets" />
  </ItemGroup>
</Project>