using System.Text.Json.Serialization;

namespace SkiaSharp.Dashboard.Services;

// ── Dashboard wrapper (generated by collector) ───────────────────

public record TriageData(
    DateTime GeneratedAt,
    int TotalCount,
    TriageSummaryStats Summary,
    List<LabelCount> ByType,
    List<LabelCount> ByArea,
    List<LabelCount> ByAction,
    List<LabelCount> BySeverity,
    List<TriagedIssue> Issues
);

public record TriageSummaryStats(
    int NeedsInvestigation,
    int Closeable,
    int QuickWins,
    int NeedsHumanReview,
    int Regressions
);

// ── Per-issue triage (schema v2.0 grouped layout) ────────────────

public record TriagedIssue(
    TriageMeta Meta,
    string Summary,
    TriageClassification Classification,
    TriageEvidence Evidence,
    TriageAnalysis Analysis,
    TriageOutput Output,
    string? Url  // added by collector
);

// ── Meta ─────────────────────────────────────────────────────────

public record TriageMeta(
    string SchemaVersion,
    int Number,
    string Repo,
    DateTime AnalyzedAt,
    List<string>? CurrentLabels
);

// ── Classification ───────────────────────────────────────────────

public record TriageClassification(
    ClassifiedField Type,
    ClassifiedField? Area,
    List<ClassifiedField>? Backends,
    List<ClassifiedField>? Platforms,
    List<ClassifiedField>? Tenets,
    ClassifiedField? Partner
);

public record ClassifiedField(
    string Value,
    double Confidence
);

// ── Evidence ─────────────────────────────────────────────────────

public record TriageEvidence(
    BugSignals? BugSignals,
    ReproEvidence? ReproEvidence,
    VersionAnalysis? VersionAnalysis,
    RegressionInfo? Regression,
    FixStatusInfo? FixStatus
);

public record BugSignals(
    bool HasCrash,
    bool HasStackTrace,
    string ReproQuality,
    bool? HasWorkaround,
    string? WorkaroundSummary,
    List<string>? TargetFrameworks,
    string Severity,
    string SeverityReason
);

public record ReproEvidence(
    List<Screenshot>? Screenshots,
    List<Attachment>? Attachments,
    List<RepoLink>? RepoLinks,
    List<int>? RelatedIssues,
    List<string>? StepsToReproduce,
    List<CodeSnippet>? CodeSnippets,
    string? EnvironmentDetails
);

public record Screenshot(string Url, string? Context, string? Source);
public record Attachment(string Url, string Filename, string? Type, string? Source);
public record RepoLink(string Url, string? Description);
public record CodeSnippet(string Code, string? Language, string? Context);

public record VersionAnalysis(
    List<string>? MentionedVersions,
    string? CurrentRelevance,
    string Reason,
    string? MigrationPath
);

public record RegressionInfo(
    bool IsRegression,
    double Confidence,
    string Reason,
    string? WorkedInVersion,
    string? BrokeInVersion
);

public record FixStatusInfo(
    bool LikelyFixed,
    double Confidence,
    string Reason,
    List<int>? RelatedPRs,
    List<string>? RelatedCommits,
    string? FixedInVersion,
    string? VerificationStatus
);

// ── Analysis ─────────────────────────────────────────────────────

public record TriageAnalysis(
    string Summary,
    List<KeySignal> KeySignals,
    List<FieldRationale> FieldRationales,
    List<string>? Uncertainties,
    List<string>? Assumptions,
    ResolutionAnalysis? Resolution
);

public record KeySignal(
    string Text,
    string Source,
    string Interpretation
);

public record FieldRationale(
    string Field,
    string Chosen,
    string ExpandedReason,
    List<Alternative>? Alternatives
);

public record Alternative(string Value, string WhyRejected);

public record ResolutionAnalysis(
    string Hypothesis,
    List<ResolutionProposal> Proposals,
    string RecommendedProposal,
    string RecommendedReason
);

public record ResolutionProposal(
    string Title,
    string Description,
    double Confidence,
    string Effort
);

// ── Output ───────────────────────────────────────────────────────

public record TriageOutput(
    Actionability Actionability,
    List<TriageAction>? Actions
);

public record Actionability(
    string SuggestedAction,
    double Confidence,
    string Reason,
    bool? RequiresHumanReview,
    List<string>? MissingInfo
);

// ── Actions ──────────────────────────────────────────────────────

public record TriageAction(
    string Id,
    string Type,
    string Risk,
    string Description,
    string Reason,
    double Confidence,
    string? DependsOn,
    System.Text.Json.JsonElement? Payload
)
{
    public UpdateLabelsPayload? GetLabelsPayload() =>
        Type == "update-labels" && Payload.HasValue
            ? System.Text.Json.JsonSerializer.Deserialize<UpdateLabelsPayload>(Payload.Value, _jsonOpts)
            : null;

    public AddCommentPayload? GetCommentPayload() =>
        Type == "add-comment" && Payload.HasValue
            ? System.Text.Json.JsonSerializer.Deserialize<AddCommentPayload>(Payload.Value, _jsonOpts)
            : null;

    public CloseIssuePayload? GetClosePayload() =>
        Type == "close-issue" && Payload.HasValue
            ? System.Text.Json.JsonSerializer.Deserialize<CloseIssuePayload>(Payload.Value, _jsonOpts)
            : null;

    public LinkDuplicatePayload? GetDuplicatePayload() =>
        Type == "link-duplicate" && Payload.HasValue
            ? System.Text.Json.JsonSerializer.Deserialize<LinkDuplicatePayload>(Payload.Value, _jsonOpts)
            : null;

    public LinkRelatedPayload? GetRelatedPayload() =>
        Type == "link-related" && Payload.HasValue
            ? System.Text.Json.JsonSerializer.Deserialize<LinkRelatedPayload>(Payload.Value, _jsonOpts)
            : null;

    private static readonly System.Text.Json.JsonSerializerOptions _jsonOpts = new()
    {
        PropertyNamingPolicy = System.Text.Json.JsonNamingPolicy.CamelCase,
        PropertyNameCaseInsensitive = true
    };
}

[JsonDerivedType(typeof(UpdateLabelsPayload))]
[JsonDerivedType(typeof(AddCommentPayload))]
[JsonDerivedType(typeof(CloseIssuePayload))]
[JsonDerivedType(typeof(LinkRelatedPayload))]
[JsonDerivedType(typeof(LinkDuplicatePayload))]
public record TriageActionPayload;

public record UpdateLabelsPayload(
    List<string>? LabelsToAdd,
    List<string>? LabelsToRemove
) : TriageActionPayload;

public record AddCommentPayload(
    string? CommentType,
    string? DraftBody,
    bool? RequiresHumanEdit,
    string? FinalBody,
    string? DedupeToken
) : TriageActionPayload;

public record CloseIssuePayload(
    string? Reason,
    string? Comment
) : TriageActionPayload;

public record LinkRelatedPayload(
    List<int>? RelatedIssues,
    string? Comment
) : TriageActionPayload;

public record LinkDuplicatePayload(
    int? DuplicateOf,
    string? Comment
) : TriageActionPayload;
