parameters:
  - name: buildAgentHost
    type: object

stages:
  - stage: prepare
    displayName: Prepare Build
    jobs:
      - job: prepare
        displayName: Prepare Build
        pool: ${{ parameters.buildAgentHost.pool }}
        steps:
          - checkout: self
            submodules: false
            fetchDepth: 1
          - pwsh: ./scripts/infra/native/shared/set-build-variables.ps1 -UpdateBuildNumber
            displayName: Configure build variables
          - pwsh: ./scripts/infra/caching/analyze-stage-changes.ps1 -Validate
            displayName: Validate cache config coverage
