parameters:
  emscripten: [ ]

jobs:
  - ${{ each version in parameters.emscripten }}:
    - template: azure-templates-bootstrapper.yml
      parameters:
        name: native_wasm_${{ replace(version, '.', '_') }}_linux
        displayName: WASM (${{ version }})
        vmImage: $(VM_IMAGE_LINUX)
        docker: scripts/Docker/wasm
        target: externals-wasm
        dockerArgs: --build-arg EMSCRIPTEN_VERSION=${{ version }}
        additionalArgs: --emscriptenVersion=${{ version }}
        postBuildSteps:
          - task: PublishBuildArtifacts@1
            displayName: Publish the native_wasm_linux artifacts
            inputs:
              artifactName: native_wasm_linux
              pathToPublish: 'output'