parameters:
  - name: buildAgentLinuxNative
    type: object
  - name: use1ESPipelineTemplates
    type: boolean
  - name: enableCaching
    type: boolean
    default: false

stages:

  - stage: native_tizen
    displayName: Native Tizen
    dependsOn: prepare
    jobs:
      - template: /scripts/azure-templates-jobs-bootstrapper.yml@self # Build Native Tizen|x64 (Linux, Docker)
        parameters:
          name: native_tizen_x64_linux
          displayName: Tizen x64
          buildAgent: ${{ parameters.buildAgentLinuxNative }}
          use1ESPipelineTemplates: ${{ parameters.use1ESPipelineTemplates }}
          docker: scripts/infra/native/tizen/docker
          target: externals-tizen
          cacheJob: native/tizen
          enableCaching: ${{ parameters.enableCaching }}
          additionalArgs: --buildarch=x64
      - template: /scripts/azure-templates-jobs-bootstrapper.yml@self # Build Native Tizen|arm64 (Linux, Docker)
        parameters:
          name: native_tizen_arm64_linux
          displayName: Tizen arm64
          buildAgent: ${{ parameters.buildAgentLinuxNative }}
          use1ESPipelineTemplates: ${{ parameters.use1ESPipelineTemplates }}
          docker: scripts/infra/native/tizen/docker
          target: externals-tizen
          cacheJob: native/tizen
          enableCaching: ${{ parameters.enableCaching }}
          additionalArgs: --buildarch=arm64
