parameters:
  name: ''                                      # in the form type_platform_host
  displayName: ''                               # the human name
  vmImage: ''                                   # the VM image
  condition: succeeded()                        # whether or not to run this template
  buildExternals: ''                            # the build number to download externals from
  postBuildSteps: []                            # any additional steps to run after the build
  artifactName: ''                              # the name of the artifact to merge this run into

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}
    pool:
      ${{ if startsWith(parameters.vmImage, 'Azure-Pipelines-') }}:
        vmImage: ${{ replace(parameters.vmImage, 'Azure-Pipelines-', '') }}
      ${{ if not(startsWith(parameters.vmImage, 'Azure-Pipelines-')) }}:
        name: ${{ parameters.vmImage }}
    condition: ${{ parameters.condition }}
    steps:
      - checkout: none
      - template: azure-templates-download-artifacts.yml
        parameters:
          sourceBuildId: ${{ parameters.buildExternals }}
          artifacts: ${{ parameters.name }}
      - task: PublishBuildArtifacts@1
        displayName: Publish the ${{ parameters.name }} artifacts
        inputs:
          artifactName: ${{ parameters.name }}
          pathToPublish: 'output'
      - ${{ if ne(parameters.artifactName, '') }}:
        - task: PublishBuildArtifacts@1
          displayName: Publish the combined ${{ parameters.artifactName }} artifacts
          inputs:
            artifactName: ${{ parameters.artifactName }}
            pathToPublish: 'output'
      - ${{ parameters.postBuildSteps }}
