parameters:
  artifactName: ''                              # the name of the artifact to merge this run into
  emscripten: [ ]

jobs:
  - ${{ each version in parameters.emscripten }}:
    - template: azure-templates-bootstrapper.yml
      parameters:
        name: native_wasm_${{ replace(version, '.', '_') }}_linux
        displayName: WASM (${{ version }})
        vmImage: $(VM_IMAGE_LINUX)
        docker: scripts/Docker/wasm
        target: externals-wasm
        dockerArgs: --build-arg EMSCRIPTEN_VERSION=${{ version }}
        additionalArgs: --emscriptenVersion=${{ version }}
        artifactName: ${{ parameters.artifactName }}