parameters:
  builds:
    - name: ''
      desc: ''
      additionalArgs: ''
      gnArgs: ''
  matrix:
    - arch: ''
      variant: ''
      docker: ''
      dockerArgs: ''
      target: ''
      gnArgs: ''

jobs:
  - ${{ each item in parameters.matrix }}:
    - ${{ each build in parameters.builds }}:
      - template: azure-templates-bootstrapper.yml
        parameters:
          name: native_${{ build.name }}_${{ item.arch }}_${{ coalesce(item.variant, 'default') }}_linux
          displayName: Build Native Linux|${{ item.arch }} [${{ coalesce(item.variant, 'default') }}|${{ build.desc }}]
          vmImage: $(VM_IMAGE_LINUX)
          docker: ${{ item.docker }}
          dockerArgs: ${{ item.dockerArgs }}
          target: ${{ coalesce(item.target, 'externals-linux') }}
          additionalArgs: --buildarch=${{ item.arch }} --variant=${{ item.variant }} ${{ item.additionalArgs }} ${{ build.additionalArgs }}