parameters:
  - name: buildAgentWindows
    type: object

stages:

  - stage: package
    displayName: Package NuGets
    dependsOn: native
    jobs:
      - template: /scripts/azure-templates-jobs-bootstrapper.yml@self # Package NuGets
        parameters:
          name: package_windows
          displayName: Package NuGets
          buildAgent: ${{ parameters.buildAgentWindows}}
          target: nuget
          additionalArgs: --skipExternals="all"
          shouldPublish: false
          requiredArtifacts:
            - name: native
          publishArtifacts:
            - name: nuget
              path: '.\output\nugets'
            - name: nuget_special
              path: '.\output\nugets-special'
            - name: arcade_shipping
              path: '.\output\arcade-assets\Shipping'
            - name: arcade_nonshipping
              path: '.\output\arcade-assets\NonShipping'
            - name: PdbArtifacts
              path: '.\output\pdbs'
              isProduction: 'false'

      - template: /scripts/azure-templates-jobs-merger.yml@self # Scan NuGet Artifacts
        parameters:
          name: scan_normal_windows
          displayName: Scan NuGet Artifacts
          buildAgent: ${{ parameters.buildAgentWindows}}
          dependsOn: package_windows
          shouldPublish: false
          requiredArtifacts:
            - name: nuget
              dir: nugets
              currentRun: true
          postBuildSteps:
            - pwsh: |
                .\scripts\infra\package\extract-nupkg-files.ps1 `
                  -SourcePath ".\output\nugets*\*.*nupkg" `
                  -DestinationPath ".\output\extracted_nugets"
              displayName: Extract all the .nupkg files for scanning
