parameters:
  - name: buildPipelineType
    type: string
  - name: buildExternals
    type: string
    default: 'latest'
  - name: buildAgentHost
    type: object
  - name: buildAgentWindows
    type: object
  - name: buildAgentWindowsNative
    type: object
  - name: buildAgentMac
    type: object
  - name: buildAgentMacNative
    type: object
  - name: buildAgentLinux
    type: object
  - name: buildAgentLinuxNative
    type: object
  - name: buildAgentAndroidTests
    type: object
  - name: sdl
    type: object
    default:
      apiscan:
        enabled: false
      binskim:
        break: false
      spotBugs:
        enabled: false
  - name: use1ESPipelineTemplates
    type: boolean
    default: false
  - name: enableSigning
    type: boolean
    default: false
  - name: forceRealSigning
    type: boolean
    default: false

stages:

  - template: /scripts/azure-templates-stages-prepare.yml@self
    parameters:
      buildAgentHost: ${{ parameters.buildAgentHost }}

  - ${{ if in(parameters.buildPipelineType, 'native', 'complete') }}:
    - template: /scripts/azure-templates-stages-native.yml@self
      parameters:
        buildAgentHost: ${{ parameters.buildAgentHost }}
        buildAgentWindowsNative: ${{ parameters.buildAgentWindowsNative }}
        buildAgentMacNative: ${{ parameters.buildAgentMacNative }}
        buildAgentLinuxNative: ${{ parameters.buildAgentLinuxNative }}
        sdl: ${{ parameters.sdl }}
        use1ESPipelineTemplates: ${{ parameters.use1ESPipelineTemplates }}
        buildExternals: ${{ parameters.buildExternals }}

  - ${{ if in(parameters.buildPipelineType, 'package', 'complete') }}:
    - template: /scripts/azure-templates-stages-package.yml@self
      parameters:
        buildAgentHost: ${{ parameters.buildAgentHost }}
        buildAgentWindows: ${{ parameters.buildAgentWindows }}
        sdl: ${{ parameters.sdl }}
        use1ESPipelineTemplates: ${{ parameters.use1ESPipelineTemplates }}
        enableSigning: ${{ parameters.enableSigning }}
        forceRealSigning: ${{ parameters.forceRealSigning }}

  - ${{ if in(parameters.buildPipelineType, 'test', 'complete') }}:
    - template: /scripts/azure-templates-stages-test.yml@self
      parameters:
        dependsOnPrepare: ${{ eq(parameters.buildPipelineType, 'test') }}
        buildAgentHost: ${{ parameters.buildAgentHost }}
        buildAgentWindows: ${{ parameters.buildAgentWindows }}
        buildAgentMac: ${{ parameters.buildAgentMac }}
        buildAgentLinux: ${{ parameters.buildAgentLinux }}
        buildAgentAndroidTests: ${{ parameters.buildAgentAndroidTests }}
