parameters:
  - name: buildAgentHost
    type: object

stages:
  - stage: prepare
    displayName: Prepare Build
    jobs:
      - job: prepare
        displayName: Prepare Build
        pool: ${{ parameters.buildAgentHost.pool }}
        steps:
          - checkout: self
            submodules: false
            fetchDepth: 1
            sparseCheckoutDirectories: scripts/set-build-variables.ps1
          - pwsh: ./scripts/set-build-variables.ps1 -UpdateBuildNumber
            displayName: Configure build variables
