parameters:
  buildExternals: ''                            # the build number to download externals from
  buildPipelineType: 'both'                     # the type of build pipeline setup
  buildAgent: ''                                # the configuration for the build agent
  use1ESPipelineTemplates: false                # whether or not we are building using the internal 1ES Pipeline Templates
  sdl: []                                       # the SDL properties to use for this job
  builds:
    - name: ''
      desc: ''
      additionalArgs: ''
      gnArgs: ''
  matrix:
    - arch: ''
      variant: ''
      docker: ''
      dockerArgs: ''
      target: ''
      gnArgs: ''
      alt: ''

jobs:
  - ${{ each build in parameters.builds }}:
    - ${{ each item in parameters.matrix }}:
      - template: /scripts/azure-templates-bootstrapper.yml@self
        parameters:
          name: ${{ replace(replace(format('native_linux_{0}_{1}_{2}_{3}_linux', item.arch, item.variant, build.name, item.alt), '__', '_'), '__', '_') }}
          displayName: Linux ${{ replace(replace(replace(replace(replace(format('({0}|{1}|{2}|{3})', item.arch, item.variant, build.name, item.alt), '||', '|'), '||', '|'), '(|', '('), '|)', ')'), '|', ', ') }}
          sdl: ${{ parameters.sdl }}
          buildExternals: ${{ parameters.buildExternals }}
          buildPipelineType: ${{ parameters.buildPipelineType }}
          buildAgent: ${{ parameters.buildAgent }}
          use1ESPipelineTemplates: ${{ parameters.use1ESPipelineTemplates }}
          docker: ${{ item.docker }}
          dockerArgs: ${{ item.dockerArgs }}
          target: ${{ coalesce(item.target, 'externals-linux') }}
          additionalArgs: --buildarch=${{ item.arch }} --variant=${{ coalesce(item.variant, 'linux') }}${{ build.name }} --gnArgs="\"${{ build.gnArgs }} ${{ item.gnArgs }}\"" ${{ build.additionalArgs }} ${{ item.additionalArgs }}