parameters:
  buildExternals: ''                            # the build number to download externals from
  buildPipelineType: false
  buildAgent: ''                                # the configuration for the build agent
  emscripten: [ ]

jobs:
  - ${{ each version in parameters.emscripten }}:
    - template: /scripts/azure-templates-bootstrapper.yml@self
      parameters:
        name: native_wasm_${{ replace(version.displayName, '.', '_') }}_linux
        displayName: WASM (${{ version.displayName }})
        buildExternals: ${{ parameters.buildExternals }}
        buildPipelineType: ${{ parameters.buildPipelineType }}
        buildAgent: ${{ parameters.buildAgent }}
        docker: scripts/Docker/wasm
        target: externals-wasm
        dockerArgs: --build-arg EMSCRIPTEN_VERSION=${{ version.version }}
        additionalArgs: --emscriptenVersion=${{ version.version }} --emscriptenFeatures="${{ version.features }}"