<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TFMPrevious)-maccatalyst$(TPVMacCatalystPrevious);$(TFMCurrent)-maccatalyst$(TPVMacCatalystCurrent)</TargetFrameworks>
    <PackagingGroup>SkiaSharp</PackagingGroup>
    <Title>$(PackagingGroup) - Native Assets for Mac Catalyst</Title>
    <HasNativeSymbolPackage>true</HasNativeSymbolPackage>
  </PropertyGroup>
  <ItemGroup>
    <PackageFile Include="$(NativeOutputPath)maccatalyst\libSkiaSharp*.framework.zip" PackagePath="runtimes\maccatalyst\native\%(Filename)%(Extension)" />
    <NativeSymbolRequiredFile Include="$(NativeOutputPath)maccatalyst\libSkiaSharp.framework.zip" />
    <NativeSymbolRequiredFile Include="$(NativeOutputPath)maccatalyst\libSkiaSharp.framework\Versions\A\libSkiaSharp" />
    <NativeSymbolPackageFile Include="$(NativeOutputPath)maccatalyst\libSkiaSharp.framework\Versions\A\libSkiaSharp" RuntimeIdentifier="maccatalyst" Architecture="universal" SymbolPackagePath="runtimes\maccatalyst\native\libSkiaSharp.framework\Versions\A" />
    <NativeSymbolBundle Include="$(NativeOutputPath)maccatalyst\libSkiaSharp\arm64.xcarchive\dSYMs\libSkiaSharp.framework.dSYM" DwarfName="libSkiaSharp" SymbolPackagePath="runtimes\maccatalyst\native\symbols\arm64\libSkiaSharp.framework.dSYM" />
    <NativeSymbolBundle Include="$(NativeOutputPath)maccatalyst\libSkiaSharp\x86_64.xcarchive\dSYMs\libSkiaSharp.framework.dSYM" DwarfName="libSkiaSharp" SymbolPackagePath="runtimes\maccatalyst\native\symbols\x86_64\libSkiaSharp.framework.dSYM" />
  </ItemGroup>
  <Target Name="IncludeAdditionalTfmSpecificPackageFiles">
    <ItemGroup>
      <TfmSpecificPackageFile Include="buildTransitive\SkiaSharp.targets" PackagePath="buildTransitive\$(NuGetShortFolderName)\$(PackageId).targets" />
    </ItemGroup>
  </Target>
</Project>