<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TFMPrevious)-maccatalyst$(TPVMacCatalystPrevious);$(TFMCurrent)-maccatalyst$(TPVMacCatalystCurrent)</TargetFrameworks>
    <PackagingGroup>SkiaSharp</PackagingGroup>
    <Title>$(PackagingGroup) - Native Assets for Mac Catalyst</Title>
    <HasNativeSymbolPackage>true</HasNativeSymbolPackage>
  </PropertyGroup>
  <ItemGroup>
    <NativeRuntimeFile Include="$(NativeOutputPath)maccatalyst\libSkiaSharp.framework.zip" PackagePath="runtimes\maccatalyst\native" />
    <NativeRuntimeFile Include="$(NativeOutputPath)maccatalyst\libSkiaSharp.framework\Versions\A\libSkiaSharp" PackagePath="runtimes\maccatalyst\native\libSkiaSharp.framework\Versions\A" PackageScope="Symbols" />
    <NativeSymbolBundle Include="$(NativeOutputPath)maccatalyst\libSkiaSharp\arm64.xcarchive\dSYMs\libSkiaSharp.framework.dSYM" DwarfName="libSkiaSharp" PackagePath="runtimes\maccatalyst\native\symbols\arm64\libSkiaSharp.framework.dSYM" />
    <NativeSymbolBundle Include="$(NativeOutputPath)maccatalyst\libSkiaSharp\x86_64.xcarchive\dSYMs\libSkiaSharp.framework.dSYM" DwarfName="libSkiaSharp" PackagePath="runtimes\maccatalyst\native\symbols\x86_64\libSkiaSharp.framework.dSYM" />
  </ItemGroup>
  <Target Name="IncludeAdditionalTfmSpecificPackageFiles">
    <ItemGroup>
      <TfmSpecificPackageFile Include="buildTransitive\SkiaSharp.targets" PackagePath="buildTransitive\$(NuGetShortFolderName)\$(PackageId).targets" />
    </ItemGroup>
  </Target>
</Project>