param(
    [Parameter(Mandatory = $true)]
    [string] $PackageDirectory
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$directory = [IO.Path]::GetFullPath($PackageDirectory)
if (-not (Test-Path $directory -PathType Container)) {
    throw "Shipping package directory does not exist: $directory"
}

$packages = @(
    Get-ChildItem $directory -Filter '*.nupkg' -File |
        Where-Object {
            -not $_.Name.EndsWith('.symbols.nupkg', [StringComparison]::OrdinalIgnoreCase)
        })
if ($packages.Count -eq 0) {
    throw "No shipping packages were found in '$directory'."
}

$generated = 0
$existing = 0
foreach ($package in $packages) {
    if ($package.Name.StartsWith('_', [StringComparison]::Ordinal)) {
        throw "Transport package '$($package.Name)' cannot enter the shipping symbol view."
    }

    $symbolName = "$($package.BaseName).symbols.nupkg"
    $symbolPath = Join-Path $directory $symbolName
    if (Test-Path $symbolPath -PathType Leaf) {
        $existing++
        continue
    }

    Copy-Item $package.FullName $symbolPath
    $generated++
}

Write-Host "Shipping symbols: $existing explicit package(s), $generated byte-identical fallback package(s)."
