<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TFMPrevious)-tvos$(TPVtvOSPrevious);$(TFMCurrent)-tvos$(TPVtvOSCurrent)</TargetFrameworks>
    <PackagingGroup>HarfBuzzSharp</PackagingGroup>
    <Title>$(PackagingGroup) - Native Assets for tvOS</Title>
    <HasNativeSymbolPackage>true</HasNativeSymbolPackage>
  </PropertyGroup>
  <ItemGroup>
    <PackageFile Include="$(NativeOutputPath)tvos\libHarfBuzzSharp.framework\**" PackagePath="runtimes\tvos\native\libHarfBuzzSharp.framework" />
    <PackageFile Include="$(NativeOutputPath)tvossimulator\libHarfBuzzSharp.framework\**" PackagePath="runtimes\tvossimulator\native\libHarfBuzzSharp.framework" />
    <NativeSymbolRequiredFile Include="$(NativeOutputPath)tvos\libHarfBuzzSharp.framework\libHarfBuzzSharp" />
    <NativeSymbolRequiredFile Include="$(NativeOutputPath)tvossimulator\libHarfBuzzSharp.framework\libHarfBuzzSharp" />
    <NativeSymbolBundle Include="$(NativeOutputPath)tvos\libHarfBuzzSharp\arm64.xcarchive\dSYMs\libHarfBuzzSharp.framework.dSYM" DwarfName="libHarfBuzzSharp" SymbolPackagePath="runtimes\tvos\native\symbols\arm64\libHarfBuzzSharp.framework.dSYM" />
    <NativeSymbolBundle Include="$(NativeOutputPath)tvos\libHarfBuzzSharp\x86_64.xcarchive\dSYMs\libHarfBuzzSharp.framework.dSYM" DwarfName="libHarfBuzzSharp" SymbolPackagePath="runtimes\tvos\native\symbols\x86_64\libHarfBuzzSharp.framework.dSYM" />
    <NativeSymbolBundle Include="$(NativeOutputPath)tvossimulator\libHarfBuzzSharp\arm64.xcarchive\dSYMs\libHarfBuzzSharp.framework.dSYM" DwarfName="libHarfBuzzSharp" SymbolPackagePath="runtimes\tvossimulator\native\symbols\arm64\libHarfBuzzSharp.framework.dSYM" />
    <NativeSymbolBundle Include="$(NativeOutputPath)tvossimulator\libHarfBuzzSharp\x86_64.xcarchive\dSYMs\libHarfBuzzSharp.framework.dSYM" DwarfName="libHarfBuzzSharp" SymbolPackagePath="runtimes\tvossimulator\native\symbols\x86_64\libHarfBuzzSharp.framework.dSYM" />
  </ItemGroup>
  <Target Name="IncludeAdditionalTfmSpecificPackageFiles">
    <ItemGroup>
      <TfmSpecificPackageFile Include="buildTransitive\HarfBuzzSharp.targets" PackagePath="buildTransitive\$(NuGetShortFolderName)\$(PackageId).targets" />
    </ItemGroup>
  </Target>
</Project>