<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TFMPrevious)-tvos$(TPVtvOSPrevious);$(TFMCurrent)-tvos$(TPVtvOSCurrent)</TargetFrameworks>
    <PackagingGroup>HarfBuzzSharp</PackagingGroup>
    <Title>$(PackagingGroup) - Native Assets for tvOS</Title>
  </PropertyGroup>
  <ItemGroup>
    <NativeRuntimeBundle Include="..\..\output\native\tvos\libHarfBuzzSharp.framework" ModuleName="libHarfBuzzSharp" PackagePath="runtimes\tvos\native\libHarfBuzzSharp.framework" />
    <NativeRuntimeBundle Include="..\..\output\native\tvossimulator\libHarfBuzzSharp.framework" ModuleName="libHarfBuzzSharp" PackagePath="runtimes\tvossimulator\native\libHarfBuzzSharp.framework" />
    <NativeSymbolBundle Include="..\..\output\native\tvos\libHarfBuzzSharp\arm64.xcarchive\dSYMs\libHarfBuzzSharp.framework.dSYM" DwarfName="libHarfBuzzSharp" PackagePath="runtimes\tvos\native\symbols\arm64\libHarfBuzzSharp.framework.dSYM" />
    <NativeSymbolBundle Include="..\..\output\native\tvos\libHarfBuzzSharp\x86_64.xcarchive\dSYMs\libHarfBuzzSharp.framework.dSYM" DwarfName="libHarfBuzzSharp" PackagePath="runtimes\tvos\native\symbols\x86_64\libHarfBuzzSharp.framework.dSYM" />
    <NativeSymbolBundle Include="..\..\output\native\tvossimulator\libHarfBuzzSharp\arm64.xcarchive\dSYMs\libHarfBuzzSharp.framework.dSYM" DwarfName="libHarfBuzzSharp" PackagePath="runtimes\tvossimulator\native\symbols\arm64\libHarfBuzzSharp.framework.dSYM" />
    <NativeSymbolBundle Include="..\..\output\native\tvossimulator\libHarfBuzzSharp\x86_64.xcarchive\dSYMs\libHarfBuzzSharp.framework.dSYM" DwarfName="libHarfBuzzSharp" PackagePath="runtimes\tvossimulator\native\symbols\x86_64\libHarfBuzzSharp.framework.dSYM" />
  </ItemGroup>
  <Target Name="IncludeAdditionalTfmSpecificPackageFiles">
    <ItemGroup>
      <TfmSpecificPackageFile Include="buildTransitive\HarfBuzzSharp.targets" PackagePath="buildTransitive\$(NuGetShortFolderName)\$(PackageId).targets" />
    </ItemGroup>
  </Target>
</Project>