<Project>

  <Import Project="$(MSBuildThisFileDirectory)SkiaSharp.Build.props" />

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);CS1570;CS1571;CS1572;CS1573;CS1574;CS1580;CS1581;CS1584;CS1587;CS1591</WarningsAsErrors>
  </PropertyGroup>

</Project>