<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <AssemblyName>SkiaSharp.Views.Maui.Controls.WPF.Tests</AssemblyName>
    <SkipGenerateAssemblyVersionInfo>true</SkipGenerateAssemblyVersionInfo>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WPF" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.41" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <ProjectReference Include="..\..\source\SkiaSharp.Views.Maui\SkiaSharp.Views.Maui.Controls.WPF\SkiaSharp.Views.Maui.Controls.WPF.csproj" />
  </ItemGroup>
</Project>
