//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("SkiaSharp.Extended")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("SkiaSharp.Extended")]
[assembly: AssemblyVersion("1.58.0.0")]
[assembly: AssemblyFileVersion("1.58.0.0")]
[assembly: AssemblyInformationalVersion("1.58.0.0-{GIT_SHA}")]
[assembly: AssemblyCopyright("Xamarin Inc.")]
[assembly: AssemblyTrademark("")]

