using System.Text.Json;
using SkiaSharp.ReleaseTool.Errors;
using SkiaSharp.ReleaseTool.Json;
using Xunit;

namespace SkiaSharp.ReleaseTool.Tests.Json
{
	public class CanonicalJsonTests
	{
		[Fact]
		public void ToCanonicalString_sorts_keys_and_uses_compact_separators()
		{
			using var doc = JsonDocument.Parse("""{"b": 2, "a": 1}""");

			Assert.Equal("""{"a":1,"b":2}""", CanonicalJson.ToCanonicalString(doc.RootElement));
		}

		[Fact]
		public void ToCanonicalString_sorts_keys_recursively_at_every_nesting_level()
		{
			using var doc = JsonDocument.Parse("""{"outer":{"z":1,"a":2}}""");

			Assert.Equal("""{"outer":{"a":2,"z":1}}""", CanonicalJson.ToCanonicalString(doc.RootElement));
		}

		[Fact]
		public void ToCanonicalString_matches_python_json_dumps_output_exactly()
		{
			// Generated by CPython:
			//   json.dumps({"b": [1, 2, {}], "a": {"x": 1, "y": []},
			//               "z": 'hello "world" / slash \u00e9 \U0001F389 \n\t control \u0001'},
			//              sort_keys=True, separators=(",", ":"), ensure_ascii=True)
			const string expected =
				"""{"a":{"x":1,"y":[]},"b":[1,2,{}],"z":"hello \"world\" / slash \u00e9 \ud83c\udf89 \n\t control \u0001"}""";
			const string input =
				"{\"b\": [1, 2, {}], \"a\": {\"x\": 1, \"y\": []}, " +
				"\"z\": \"hello \\\"world\\\" / slash \u00e9 \U0001F389 \\n\\t control \\u0001\"}";
			using var doc = JsonDocument.Parse(input);

			Assert.Equal(expected, CanonicalJson.ToCanonicalString(doc.RootElement));
		}

		[Fact]
		public void ToCanonicalString_excludes_the_top_level_property_only()
		{
			using var doc = JsonDocument.Parse("""{"planDigest":"abc","nested":{"planDigest":"keep-me"}}""");

			Assert.Equal(
				"""{"nested":{"planDigest":"keep-me"}}""",
				CanonicalJson.ToCanonicalString(doc.RootElement, excludeTopLevelProperty: "planDigest"));
		}

		[Fact]
		public void ToCanonicalString_rejects_floating_point_numbers()
		{
			using var doc = JsonDocument.Parse("""{"value":1.5}""");

			Assert.Throws<ValidationException>(() => CanonicalJson.ToCanonicalString(doc.RootElement));
		}

		[Fact]
		public void ToCanonicalString_accepts_whole_integers()
		{
			using var doc = JsonDocument.Parse("""{"value":42}""");

			Assert.Equal("""{"value":42}""", CanonicalJson.ToCanonicalString(doc.RootElement));
		}

		[Fact]
		public void ComputeSha256Hex_is_deterministic_regardless_of_source_key_order()
		{
			using var docA = JsonDocument.Parse("""{"a":1,"b":2}""");
			using var docB = JsonDocument.Parse("""{"b":2,"a":1}""");

			Assert.Equal(CanonicalJson.ComputeSha256Hex(docA.RootElement), CanonicalJson.ComputeSha256Hex(docB.RootElement));
			Assert.Matches("^[0-9a-f]{64}$", CanonicalJson.ComputeSha256Hex(docA.RootElement));
		}

		[Fact]
		public void ToPrettyString_matches_python_json_dumps_indent_2_output_exactly()
		{
			// Generated by CPython:
			//   json.dumps({"b": [1, 2, {}], "a": {"x": 1, "y": []},
			//               "z": 'hello "world" / slash \u00e9 \U0001F389 \n\t control \u0001'},
			//              indent=2, sort_keys=True)
			const string expected =
				"{\n" +
				"  \"a\": {\n" +
				"    \"x\": 1,\n" +
				"    \"y\": []\n" +
				"  },\n" +
				"  \"b\": [\n" +
				"    1,\n" +
				"    2,\n" +
				"    {}\n" +
				"  ],\n" +
				"  \"z\": \"hello \\\"world\\\" / slash \\u00e9 \\ud83c\\udf89 \\n\\t control \\u0001\"\n" +
				"}";
			var json = JsonSerializer.Serialize(new Dictionary<string, object>
			{
				["b"] = new object[] { 1, 2, new Dictionary<string, object>() },
				["a"] = new Dictionary<string, object> { ["x"] = 1, ["y"] = Array.Empty<object>() },
				["z"] = "hello \"world\" / slash \u00e9 \U0001F389 \n\t control \u0001",
			});
			using var doc = JsonDocument.Parse(json);

			Assert.Equal(expected, CanonicalJson.ToPrettyString(doc.RootElement));
		}

		[Fact]
		public void ToPrettyString_collapses_empty_object_and_array_without_a_newline()
		{
			using var doc = JsonDocument.Parse("""{"o":{},"a":[]}""");

			Assert.Equal("{\n  \"a\": [],\n  \"o\": {}\n}", CanonicalJson.ToPrettyString(doc.RootElement));
		}
	}
}
