//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("SkiaSharp.Svg")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("SkiaSharp.Svg")]
[assembly: AssemblyVersion("1.55.0.0")]
[assembly: AssemblyFileVersion("1.55.1.0")]
[assembly: AssemblyInformationalVersion("1.55.1.0-{GIT_SHA}")]
[assembly: AssemblyCopyright("Xamarin Inc.")]
[assembly: AssemblyTrademark("")]

