name: Sync - Issue Template Versions

on:
  schedule:
    - cron: "0 9 * * *"  # Daily at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-update-issue-template-versions
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Require main
        run: test "$GITHUB_REF" = "refs/heads/${{ github.event.repository.default_branch }}"

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Update
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
        run: |
          ./scripts/infra/publishing/update-bug-template.ps1 `
            -Repository $env:REPOSITORY `
            -Push *>&1 |
            Tee-Object -FilePath $env:GITHUB_STEP_SUMMARY -Append
