name: PR - Backport

# Comment `/backport to <branch>` or `/backport <branch>` on a merged pull request.
on:
  issue_comment:
    types:
      - created
  schedule:
    # Once a day at 13:00 UTC to clean up completed runs of this workflow.
    - cron: '0 13 * * *'

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  backport:
    uses: dotnet/arcade/.github/workflows/backport-base.yml@306225d7029934938d109e18df390f04e366a68d # main as of 2026-08-31
    with:
      repository_owners: mono,dotnet # Remove mono after the repository transfer.
      pr_title_template: '[%target_branch%] %source_pr_title%'
      pr_description_template: 'Backport of #%source_pr_number% to %target_branch%'
      pr_labels: backport
