name: Apply labels using AI

on:
  issues:
    types: [opened, reopened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to triage'
        required: true
        type: number

jobs:
  apply-label-and-add-comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      models: read
    steps:

      - name: Determine AREA labels
        uses: mattleibow/triage-assistant@v0
        with:
          issue: ${{ inputs.issue_number || github.event.issue.number }}
          label-prefix: 'area/'
          template: 'single-label'

      - name: Determine PLATFORM labels
        uses: mattleibow/triage-assistant@v0
        with:
          issue: ${{ inputs.issue_number || github.event.issue.number }}
          label-prefix: 'os/'
          template: 'multi-label'

      - name: Determine BACKEND labels
        uses: mattleibow/triage-assistant@v0
        with:
          issue: ${{ inputs.issue_number || github.event.issue.number }}
          label-prefix: 'backend/'
          template: 'multi-label'

      - name: Determine TENET labels
        uses: mattleibow/triage-assistant@v0
        with:
          issue: ${{ inputs.issue_number || github.event.issue.number }}
          label-prefix: 'tenet/'
          template: 'single-label'

      - name: Apply all labels and add comment
        uses: mattleibow/triage-assistant@v0
        with:
          issue: ${{ inputs.issue_number || github.event.issue.number }}
          apply-labels: false
          apply-comment: false
